# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DSPDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end

  # Pods for DSPDemo
#   pod 'DSPSDK'#, :path => '../'
#   pod 'MKConsole'#log工具，项目中无需引入
  target 'DSPDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DSPDemoUITests' do
    # Pods for testing
  end

end
